services:

  db:
    image: postgres:17-alpine # Utiliza la imagen oficial de PostgreSQL en su versión 17-alpine
    container_name: planillas_db # Nombre del contenedor para la base de datos
    ports:
      - "5432:5432" # Expone el puerto 5432 para acceder a la base de datos
    environment:
      - POSTGRES_USER=postgres # Usuario de la base de datos
      - POSTGRES_PASSWORD=bella # Contraseña del usuario de la base de datos
      - POSTGRES_DB=planillas_db # Nombre de la base de datos
    volumes:
      - postgres_payroll_data:/var/lib/postgresql/data # Monta un volumen para persistir los datos de la base de datos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planillas_db"] # Se añade la flag -d para asegurar la salud sobre la BD específica
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: planillas_pgbouncer
    ports:
      - "6432:5432" # Puerto 6432 para que NestJS se conecte aquí
    environment:
      # Conecta PgBouncer a la base de datos física usando el DNS interno de Docker ("db")
      - DATABASE_URL=postgres://postgres:bella@db:5432/planillas_db
      - POOL_MODE=transaction # Modo estricto requerido por Prisma
      - MAX_CLIENT_CONN=1000  # Soporta hasta 1000 conexiones lógicas de NestJS
      - DEFAULT_POOL_SIZE=20  # Usa solo 20 conexiones físicas reales hacia Postgres
    depends_on:
      db:
        condition: service_healthy # Espera a que Postgres esté listo

  redis:
    image: redis:7-alpine # Utiliza la imagen oficial de Redis en su versión 7-alpine
    container_name: planillas_redis # Nombre del contenedor para Redis
    ports: 
      - "6379:6379" # Expone el puerto 6379 para acceder a Redis
    volumes:
      - redis_payroll_data:/data # Monta un volumen para persistir los datos de Redis
    command: redis-server --appendonly yes # Opcional: Asegura que Redis guarde las colas en disco de forma persistente
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_payroll_data: # Define el volumen para almacenar los datos de la base de datos de manera persistente
  redis_payroll_data: # Define el volumen para almacenar los datos de Redis y persistir colas de trabajo (jobs) 