Metadata del proyecto

sonar.projectKey=bella-planillas-backend
sonar.projectName=Bella Planillas Backend
sonar.projectVersion=1.0

Directorios de código fuente y pruebas

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=/.spec.ts, /.e2e-spec.ts

Codificación de caracteres

sonar.sourceEncoding=UTF-8

Exclusiones del análisis estático

sonar.exclusions=/node_modules/, dist/, coverage/, /*.spec.ts, /prisma/migrations/


Ruta del reporte de cobertura LCOV generado por Jest

sonar.typescript.lcov.reportPaths=coverage/lcov.info